name: Checks

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.5.9
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --locked
      - run: uv run --locked pytest
      - run: uv run --locked ruff check .
      - run: uv run --locked ruff format --check .
